#!/bin/sh
. "$(dirname -- "$0")/husky.sh" #허스키 초기화

echo 'lint 검사중...'

pnpm lint

changed_files=$(git diff --name-only --staged)

if [ $? -ne 0 ]; then
  echo "lint 에러 발생! 변경된 파일을 가져오는 중 오류가 발생했습니다."
  exit 1
fi

# 변경된 파일들을 다시 스테이징합니다.
echo "$changed_files" | while IFS= read -r file; do
  git add "$file"
done

if [ $? -ne 0 ]; then
  echo "lint 에러 발생! 파일을 다시 스테이징하는 중 오류가 발생했습니다."
  exit 1
fi

echo 'lint 성공!'
